"""add action_approvals

Revision ID: 6a1a9d631491
Revises: 0001
Create Date: 2026-10-07 12:21:39.800327

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from app.db.base import UTCDateTime

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_approvals',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('triage_result_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('proposed_by', sa.Uuid(), nullable=False),
    sa.Column('approved_l1_by', sa.Uuid(), nullable=True),
    sa.Column('approved_l1_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('approved_l2_by', sa.Uuid(), nullable=True),
    sa.Column('approved_l2_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.Uuid(), nullable=True),
    sa.Column('rejected_reason', sa.String(length=500), nullable=True),
    sa.Column('executed_by', sa.Uuid(), nullable=True),
    sa.Column('executed_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('execution_mode', sa.String(length=16), nullable=True),
    sa.Column('execution_result', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_action_approvals_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_l1_by'], ['users.id'], name=op.f('fk_action_approvals_approved_l1_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_l2_by'], ['users.id'], name=op.f('fk_action_approvals_approved_l2_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], name=op.f('fk_action_approvals_executed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], name=op.f('fk_action_approvals_proposed_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], name=op.f('fk_action_approvals_rejected_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triage_result_id'], ['triage_results.id'], name=op.f('fk_action_approvals_triage_result_id_triage_results'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_approvals'))
    )
    with op.batch_alter_table('action_approvals', schema=None) as batch_op:
        batch_op.create_index('ix_actions_alert', ['alert_id'], unique=False)
        batch_op.create_index('ix_actions_tenant_status', ['tenant_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_approvals', schema=None) as batch_op:
        batch_op.drop_index('ix_actions_tenant_status')
        batch_op.drop_index('ix_actions_alert')

    op.drop_table('action_approvals')
    # ### end Alembic commands ###
